 export const sampleCarriers =[
  {
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},
{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},
{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},
{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},
{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
},{
  "legalName": "Comapny 1 Ltd.",
  "matchType": "P",
  "country": "India",
  "state": "MH",
  "companyType": "CType1",
  "willisCode": "WC001",
  "lorsCode": "LC001",
  "naicCode": "111",
  "aiinCode": "AA-1111111",
  "amBest": "lorem ipsum",
  "snp": "lorem ipsum",
  "moodys": "-",
  "fitch": "-",
  "asOnDate": "Mar 2014",
  "capacity": "1122.33",
  "nwp": "1234.56",
  "combinedRatio": "11",
  "approvalStatus": "AppStatus1",
  "sanctionStatus": "-",
  "tobaEndDate": "-",
  "tobaIndicator": "N",
  "fatcaStatus": "Y"
}]